spring:
  liquibase:
    enabled: true

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sea-battle}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    jwt:
      private-key: ${JWT_SIGN_KEY:testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest}
      access-token:
        live-time: 30m
      refresh-token:
        live-time: 30D
    telegram:
      bot-token: ${TELEGRAM_BOT_TOKEN:12345:trvbccgdgfgdfgd}
app:
  cron:
    delete-revoked-tokens: 0 0 0 * * *
    delete-expired-rooms: 0 0 * * * *